In [8]:
# Start with installing the packages this notebook needs.
# comment added wednesday
import numpy as np
import pandas as pd
import time
import joblib
import matplotlib.pyplot as plt

%matplotlib inline

from sklearn.cross_validation import cross_val_predict
from sklearn import ensemble
from sklearn.ensemble import RandomForestRegressor
from sklearn import cross_validation
from sklearn.metrics import mean_squared_error
from sklearn.cross_validation import train_test_split
from sklearn.grid_search import GridSearchCV
 
train = pd.read_csv("/mnt/customer_transactions.csv", sep=",")
cols = train.columns[:11]

X_train, X_test, y_train, y_test = train_test_split(train[cols], train.flagged, test_size=0.05, random_state=42)

print(train.shape)
train.head()

(1599, 12)

,Customer value score,propensity to buy per month,buying pattern match,trailing_90_day_spend,views on product,days since last seen,days since last purchase,loyalty,likelyhood_male,browser,connection type,flagged
0,7.4,0.99,2.2,1.9,0.076,13.0,34.0,0.9978,3.51,0.56,9.4,0
1,7.8,0.88,3.2,2.6,0.098,343.0,350.0,0.9968,3.20,0.68,9.8,1
2,7.8,0.76,0.4,2.3,0.092,2.0,54.0,0.9970,3.26,0.65,9.8,1
3,11.2,0.28,5.6,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,0
4,7.4,0.70,0.0,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,0

In [1]:
import pandas as pd

train = pd.read_csv("/mnt/Walter/Transactions/churn.csv", sep=",")
cols = train.columns[:22]

print(train.shape)
train.head()

(5000, 22)

,Unnamed: 0,state,account_length,area_code,international_plan,voice_mail_plan,number_vmail_messages,total_day_minutes,total_day_calls,total_day_charge,...,total_eve_charge,total_night_minutes,total_night_calls,total_night_charge,total_intl_minutes,total_intl_calls,total_intl_charge,number_customer_service_calls,churn,fold
0,1,HI,101,area_code_510,no,no,0,70.9,123,12.05,...,18.01,236.0,73,10.62,10.6,3,2.86,3,no,Test
1,2,MT,137,area_code_510,no,no,0,223.6,86,38.01,...,20.81,94.2,81,4.24,9.5,7,2.57,0,no,Test
2,3,OH,103,area_code_408,no,yes,29,294.7,95,50.10,...,20.17,300.3,127,13.51,13.7,6,3.70,1,no,Test
3,4,NM,99,area_code_415,no,no,0,216.8,123,36.86,...,10.74,220.6,82,9.93,15.7,2,4.24,1,no,Test
4,5,SC,108,area_code_415,no,no,0,197.4,78,33.56,...,10.54,204.5,107,9.20,7.7,4,2.08,2,no,Test

In [ ]:
tuned_parameters = {'n_estimators': [60, 250, 500, 1000, 2500], 
                    'max_features':["auto", "sqrt", "log2"], 
                    'max_depth': [None, 2, 5], 
                    'min_samples_split': [1, 2, 3]}

clf = GridSearchCV(ensemble.RandomForestRegressor(), tuned_parameters, cv=5, scoring='r2', n_jobs=-1, verbose=1)
clf.fit(X_train, y_train)
print clf.best_estimator_


#clf = RandomForestRegressor(n_estimators=500, oob_score=True, n_jobs=-1)
# add a comment here
# and here.
#start = time.time()
#clf.fit(X_train, y_train)

#print "training time:", time.time() - start

#joblib.dump(clf, 'results/classifier.pkl')

Fitting 5 folds for each of 135 candidates, totalling 675 fits

[Parallel(n_jobs=-1)]: Done  34 tasks      | elapsed:   35.6s

In [ ]:
n, bins, patches = plt.hist(train.flagged)
plt.show()

In [ ]:
preds = clf.predict(X_test)

foo=plt.scatter(preds,y_test)

In [ ]:
predicted = cross_val_predict(clf.best_estimator_, train[cols], train.quality, cv=5)

fig, ax = plt.subplots()
ax.scatter(train.quality, predicted)
ax.plot([train.quality.min(), train.quality.max()], [train.quality.min(), train.quality.max()], 'k--', lw=4)
ax.set_xlabel('Measured')
ax.set_ylabel('Predicted')
plt.show()

In [ ]:
from sklearn.learning_curve import learning_curve

def plot_learning_curve(estimator, title, X, y, ylim=None, cv=None,
                        n_jobs=1, train_sizes=np.linspace(.1, 1.0, 5)):
    plt.figure()
    plt.title(title)
    if ylim is not None:
        plt.ylim(*ylim)
    plt.xlabel("Training examples")
    plt.ylabel("Score")
    train_sizes, train_scores, test_scores = learning_curve(
        estimator, X, y, cv=cv, n_jobs=n_jobs, train_sizes=train_sizes)
    train_scores_mean = np.mean(train_scores, axis=1)
    train_scores_std = np.std(train_scores, axis=1)
    test_scores_mean = np.mean(test_scores, axis=1)
    test_scores_std = np.std(test_scores, axis=1)
    plt.grid()

    plt.fill_between(train_sizes, train_scores_mean - train_scores_std,
                     train_scores_mean + train_scores_std, alpha=0.1,
                     color="r")
    plt.fill_between(train_sizes, test_scores_mean - test_scores_std,
                     test_scores_mean + test_scores_std, alpha=0.1, color="g")
    plt.plot(train_sizes, train_scores_mean, 'o-', color="r",
             label="Training score")
    plt.plot(train_sizes, test_scores_mean, 'o-', color="g",
             label="Cross-validation score")

    plt.legend(loc="best")
    return plt

estimator = clf.best_estimator_

myplot = plot_learning_curve(estimator, "Learning Curve (Random Forest)", X_train, y_train)

In [ ]:
import datetime

now = datetime.datetime.now()

print
print "The last run of this notebook was on:" 
print now.strftime("%Y-%m-%d %H:%M")